### ISSUE TITLE
Windows Updateでmkrefsが使用できなくなる

### ISSUE THREAD

**Issue by yoiyamigentouzoushi** [0xbadfca11/mkrefs#2]
10月に入ってからフォーマットをしようとすると、
「指定されたモジュールが見つかりません。」と表示されて
フォーマットできなくなりました。

軽く見た感じだとuRefsのIsRefsFormatEnabledの
SymFromNameで失敗しているようです。

参考までに。

**Comment by 0xbadfca11** [comment]
17763.832
18362.449
19008.1000
で試しましたが問題を確認できません。

エラーは「指定されたモジュールが見つかりません。」とのことですが
1. 指定したシンボルが見つからない
2. symsrv.dll が無い
3. msdl.microsoft.com から PDB ファイルをダウンロードできない
4. msdl.microsoft.com からダウンロードする設定になっていない環境変数 _NT_SYMBOL_PATH が設定されている
等はすべてが当該エラーになるため原因を 1 つに断定できません。
一時的なものでない場合 mkrefs.exe のネットワークアクセスがファイアウォールでブロックされている、DNS サーバーが腐っているなどありますのでブラウザで https://msdl.microsoft.com/download/symbols を開いて正しくエラーページが表示されるかなど確認してください。

**Comment by yoiyamigentouzoushi** [comment]
1903/1909のどちらもフォーマットできなくなっていたので、
Windows Updateが原因かと思い込んでました。
再確認しました。
結果としてOKになっていたため、一時的な症状だったようです。

(PC1) 1903 18362.418
2019/10/上旬 OK
2019/10/28 NG
2019/11/01 OK

(PC2) 1909 18363.449
2019/10/上旬 OK
2019/10/28 NG
2019/11/01 OK

おそらく
> 3.msdl.microsoft.com から PDB ファイルをダウンロードできない

あたりだと思います。
失礼しました。
